[versions]
agp = "8.7.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
workRuntime = "2.11.0"
playServicesMeasurementApi = "23.0.0"
coreKtx = "1.15.0"
coreSplashscreen = "1.0.1"
room = "2.6.1"
gson = "2.11.0"
firebaseBom = "33.9.0"
playServicesAds = "23.6.0"
billing = "9.1.0"
webkit = "1.12.1"
viewpager2 = "1.1.0"
shimmer = "0.5.0"
flexbox = "3.0.0"
securityCrypto = "1.1.0-alpha06"
picasso = "2.8"
playServicesAuth = "21.5.1"
googleApiClientAndroid = "2.7.0"
googleApiServicesDrive = "v3-rev20230212-2.0.0"
credentials = "1.6.0"
googleid = "1.2.0"
playIntegrity = "1.6.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "workRuntime" }
play-services-measurement-api = { group = "com.google.android.gms", name = "play-services-measurement-api", version.ref = "playServicesMeasurementApi" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }
firebase-database = { group = "com.google.firebase", name = "firebase-database" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-functions = { group = "com.google.firebase", name = "firebase-functions" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playServicesAds" }
billingclient = { group = "com.android.billingclient", name = "billing", version.ref = "billing" }
play-integrity = { group = "com.google.android.play", name = "integrity", version.ref = "playIntegrity" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "shimmer" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
androidx-security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
google-api-client-android = { group = "com.google.api-client", name = "google-api-client-android", version.ref = "googleApiClientAndroid" }
google-api-services-drive = { group = "com.google.apis", name = "google-api-services-drive", version.ref = "googleApiServicesDrive" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }

[plugins]
android-application = { id = "com.android.application", version = "8.11.1" }

